[package]
name = "lootcli"
version = "0.1.0"
authors = ["Christian Fries <christian.fries123@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
clap = "3.0.0-beta.2"
log = "0.4"
simple_logger = "1.11"